"""empty message

Revision ID: 023feac75202
Revises: 37bfed788221
Create Date: 2020-08-14 17:19:02.100263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023feac75202'
down_revision = '37bfed788221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deleted_doctors', 'address',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('deleted_doctors', 'qualification',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('deleted_patients', 'address',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('doctor', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('temporary_role_users', 'address',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('temporary_users', 'qualification',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('user_role', 'address',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('temporary_users', 'qualification',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('temporary_role_users', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('doctor', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('deleted_patients', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('deleted_doctors', 'qualification',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('deleted_doctors', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
