"""empty message

Revision ID: 12f6ff163096
Revises: 63f885c53065
Create Date: 2020-08-01 18:38:16.480553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f6ff163096'
down_revision = '63f885c53065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('treat_id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.String(), nullable=False),
    sa.Column('doctor_username', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_queue_doctor_username'), 'patient_queue', ['doctor_username'], unique=False)
    op.create_index(op.f('ix_patient_queue_username'), 'patient_queue', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_queue_username'), table_name='patient_queue')
    op.drop_index(op.f('ix_patient_queue_doctor_username'), table_name='patient_queue')
    op.drop_table('patient_queue')
    # ### end Alembic commands ###
