"""empty message

Revision ID: 1f1f974f394d
Revises: b0e3cc223452
Create Date: 2020-04-23 13:09:12.525822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1f974f394d'
down_revision = 'b0e3cc223452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_doctors', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    op.add_column('deleted_patients', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deleted_patients', 'deleted_on')
    op.drop_column('deleted_doctors', 'deleted_on')
    # ### end Alembic commands ###
