"""empty message

Revision ID: 37bfed788221
Revises: b38b3d20dfeb
Create Date: 2020-08-14 17:16:51.892702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bfed788221'
down_revision = 'b38b3d20dfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compounder_queue', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100))
    op.alter_column('deleted_doctors', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100))
    op.alter_column('deleted_patients', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100))
    op.alter_column('doctor', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('doctor', 'qualification',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('doctor', 'specialization',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('doctor', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('doctor', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('doctor', 'visiting_hours',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('is_user_deleted', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100))
    op.alter_column('past_user_role', 'doctor_username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('past_user_role', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('past_user_role', 'work_timings',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('patient', 'address',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('patient', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('patient_queue', 'doctor_username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('patient_queue', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('specialization', 'specialization',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150))
    op.alter_column('temporary_role_users', 'doctor_username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('temporary_role_users', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('temporary_role_users', 'work_timings',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('temporary_users', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100))
    op.alter_column('upload_medical_records', 'filename',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('upload_medical_records', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100))
    op.alter_column('user_role', 'doctor_username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user_role', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user_role', 'work_timings',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'work_timings',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user_role', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('user_role', 'doctor_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64))
    op.alter_column('user', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('upload_medical_records', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('upload_medical_records', 'filename',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('temporary_users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64))
    op.alter_column('temporary_role_users', 'work_timings',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('temporary_role_users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('temporary_role_users', 'doctor_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('specialization', 'specialization',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50))
    op.alter_column('patient_queue', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('patient_queue', 'doctor_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('patient', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('patient', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('past_user_role', 'work_timings',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('past_user_role', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('past_user_role', 'doctor_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('is_user_deleted', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64))
    op.alter_column('doctor', 'visiting_hours',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('doctor', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('doctor', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('doctor', 'specialization',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('doctor', 'qualification',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('doctor', 'contact_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('deleted_patients', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64))
    op.alter_column('deleted_doctors', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64))
    op.alter_column('compounder_queue', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64))
    # ### end Alembic commands ###
