"""empty message

Revision ID: 3d4fb455a635
Revises: 3e871b934dc1
Create Date: 2020-07-16 21:05:05.296570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4fb455a635'
down_revision = '3e871b934dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_users', 'role')
    # ### end Alembic commands ###
