"""empty message

Revision ID: 3e507a43fcd8
Revises: edf31579acd4
Create Date: 2020-08-05 20:03:47.172720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e507a43fcd8'
down_revision = 'edf31579acd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'status')
    # ### end Alembic commands ###
