"""empty message

Revision ID: 3e871b934dc1
Revises: 715a5b32dfc5
Create Date: 2020-07-16 20:36:34.929327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e871b934dc1'
down_revision = '715a5b32dfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_temporary_users_email'), 'temporary_users', ['email'], unique=True)
    op.create_index(op.f('ix_temporary_users_username'), 'temporary_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_users_username'), table_name='temporary_users')
    op.drop_index(op.f('ix_temporary_users_email'), table_name='temporary_users')
    op.drop_table('temporary_users')
    # ### end Alembic commands ###
