"""empty message

Revision ID: 412934032d4a
Revises: 12f6ff163096
Create Date: 2020-08-02 18:54:05.609784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412934032d4a'
down_revision = '12f6ff163096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('patient', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'timestamp')
    op.drop_column('patient', 'birthdate')
    # ### end Alembic commands ###
