"""empty message

Revision ID: 67cada913a00
Revises: 898284346a71
Create Date: 2020-03-28 12:51:38.261331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cada913a00'
down_revision = '898284346a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('gender_doctor', sa.String(length=15), nullable=True))
    op.add_column('patient', sa.Column('gender_user', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'gender_user')
    op.drop_column('doctor', 'gender_doctor')
    # ### end Alembic commands ###
