"""empty message

Revision ID: 715a5b32dfc5
Revises: eab571de2356
Create Date: 2020-04-29 19:01:31.619056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715a5b32dfc5'
down_revision = 'eab571de2356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_report', sa.Column('file_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_report', 'file_name')
    # ### end Alembic commands ###
