"""empty message

Revision ID: 87c317011d3f
Revises: bb9c7e5057b6
Create Date: 2020-03-27 16:28:05.186691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c317011d3f'
down_revision = 'bb9c7e5057b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('specialization', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('specialization')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialization')
    # ### end Alembic commands ###
