"""empty message

Revision ID: 898284346a71
Revises: 87c317011d3f
Create Date: 2020-03-28 12:46:13.925999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898284346a71'
down_revision = '87c317011d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(length=15), nullable=True),
    sa.Column('contact_number', sa.Unicode(length=20), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(length=15), nullable=False),
    sa.Column('specialization', sa.String(length=20), nullable=False),
    sa.Column('consultant_fee', sa.Float(), nullable=False),
    sa.Column('visiting_hours', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_username'), 'doctor', ['username'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(length=15), nullable=True),
    sa.Column('contact_number', sa.Unicode(length=20), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_username'), 'patient', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_username'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_username'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
