"""empty message

Revision ID: 8b6ef63730a1
Revises: 978ff91777f0
Create Date: 2020-07-27 12:58:15.539400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6ef63730a1'
down_revision = '978ff91777f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_users', sa.Column('contact_number', sa.String(length=15), nullable=True))
    op.add_column('temporary_users', sa.Column('experience', sa.String(length=15), nullable=True))
    op.add_column('temporary_users', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('temporary_users', sa.Column('qualification', sa.String(length=100), nullable=True))
    op.add_column('temporary_users', sa.Column('specialization', sa.String(length=20), nullable=True))
    op.alter_column('temporary_users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temporary_users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('temporary_users', 'specialization')
    op.drop_column('temporary_users', 'qualification')
    op.drop_column('temporary_users', 'name')
    op.drop_column('temporary_users', 'experience')
    op.drop_column('temporary_users', 'contact_number')
    # ### end Alembic commands ###
