"""empty message

Revision ID: 8be48423c177
Revises: a763c1efec41
Create Date: 2020-08-12 22:26:23.394565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be48423c177'
down_revision = 'a763c1efec41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('File', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'File')
    # ### end Alembic commands ###
