"""empty message

Revision ID: 91c4538ecc67
Revises: e6a26c208b3e
Create Date: 2020-08-06 16:59:19.159465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c4538ecc67'
down_revision = 'e6a26c208b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temporary_role_users_username_fkey', 'temporary_role_users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('temporary_role_users_username_fkey', 'temporary_role_users', 'user', ['username'], ['username'])
    # ### end Alembic commands ###
