"""empty message

Revision ID: 978ff91777f0
Revises: 3d4fb455a635
Create Date: 2020-07-17 15:21:15.876692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978ff91777f0'
down_revision = '3d4fb455a635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
