"""empty message

Revision ID: a763c1efec41
Revises: b57a1c05d1ee
Create Date: 2020-08-12 13:23:52.653986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a763c1efec41'
down_revision = 'b57a1c05d1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_medical_records', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_medical_records', 'name')
    # ### end Alembic commands ###
