"""empty message

Revision ID: a7f8bce5d8e0
Revises: 8be48423c177
Create Date: 2020-08-13 20:07:50.686296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f8bce5d8e0'
down_revision = '8be48423c177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_doctors', sa.Column('File', sa.LargeBinary(), nullable=True))
    op.add_column('deleted_patients', sa.Column('File', sa.LargeBinary(), nullable=True))
    op.add_column('doctor', sa.Column('File', sa.LargeBinary(), nullable=True))
    op.add_column('past_user_role', sa.Column('File', sa.LargeBinary(), nullable=True))
    op.add_column('temporary_role_users', sa.Column('File', sa.LargeBinary(), nullable=True))
    op.add_column('temporary_users', sa.Column('File', sa.LargeBinary(), nullable=True))
    op.add_column('user_role', sa.Column('File', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'File')
    op.drop_column('temporary_users', 'File')
    op.drop_column('temporary_role_users', 'File')
    op.drop_column('past_user_role', 'File')
    op.drop_column('doctor', 'File')
    op.drop_column('deleted_patients', 'File')
    op.drop_column('deleted_doctors', 'File')
    # ### end Alembic commands ###
