"""empty message

Revision ID: ab442f90b78f
Revises: fcaf49dbee14
Create Date: 2020-08-10 20:52:41.528721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab442f90b78f'
down_revision = 'fcaf49dbee14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_user_role', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_user_role', 'role')
    # ### end Alembic commands ###
