"""empty message

Revision ID: b57a1c05d1ee
Revises: ab442f90b78f
Create Date: 2020-08-11 19:38:19.950347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b57a1c05d1ee'
down_revision = 'ab442f90b78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_report',
    sa.Column('treat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pres_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('report', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('treat_id', 'pres_id', 'report_name', name='upload_report_pkey')
    )
    # ### end Alembic commands ###
