"""empty message

Revision ID: bfbe171e7b2e
Revises: e431ecc52f0f
Create Date: 2020-04-23 11:21:42.994544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbe171e7b2e'
down_revision = 'e431ecc52f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_doctors_email', table_name='deleted_doctors')
    op.drop_index('ix_deleted_doctors_timestamp', table_name='deleted_doctors')
    op.create_unique_constraint(None, 'deleted_doctors', ['email'])
    op.drop_index('ix_deleted_patients_email', table_name='deleted_patients')
    op.create_unique_constraint(None, 'deleted_patients', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deleted_patients', type_='unique')
    op.create_index('ix_deleted_patients_email', 'deleted_patients', ['email'], unique=True)
    op.drop_constraint(None, 'deleted_doctors', type_='unique')
    op.create_index('ix_deleted_doctors_timestamp', 'deleted_doctors', ['timestamp'], unique=False)
    op.create_index('ix_deleted_doctors_email', 'deleted_doctors', ['email'], unique=True)
    # ### end Alembic commands ###
