"""empty message

Revision ID: d5455000d948
Revises: 8b6ef63730a1
Create Date: 2020-07-27 12:58:54.644641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5455000d948'
down_revision = '8b6ef63730a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_users', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_temporary_users_timestamp'), 'temporary_users', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_users_timestamp'), table_name='temporary_users')
    op.drop_column('temporary_users', 'timestamp')
    # ### end Alembic commands ###
