"""empty message

Revision ID: eab571de2356
Revises: b8a2bf42b347
Create Date: 2020-04-29 13:01:59.360960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab571de2356'
down_revision = 'b8a2bf42b347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_report',
    sa.Column('treat_id', sa.Integer(), nullable=False),
    sa.Column('pres_id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=50), nullable=False),
    sa.Column('report', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('treat_id', 'pres_id', 'report_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_report')
    # ### end Alembic commands ###
