"""empty message

Revision ID: edf31579acd4
Revises: 39ad28d34253
Create Date: 2020-08-04 17:04:45.819583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf31579acd4'
down_revision = '39ad28d34253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounder_queue',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_compounder_queue_username'), 'compounder_queue', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compounder_queue_username'), table_name='compounder_queue')
    op.drop_table('compounder_queue')
    # ### end Alembic commands ###
