"""empty message

Revision ID: fcaf49dbee14
Revises: f7151fd2f78e
Create Date: 2020-08-09 22:42:43.510232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaf49dbee14'
down_revision = 'f7151fd2f78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_patients', sa.Column('joined_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deleted_patients', 'joined_on')
    # ### end Alembic commands ###
